import { ConsentTemplate } from "./types";

export const mockTemplates: ConsentTemplate[] = [
    {
        id: "tpl-001",
        name: "Marketing Communications Consent",
        description: "Consent for receiving promotional emails and newsletters",
        type: "optional",
        regulations: ["DPDP", "GDPR"],
        purposes: [{ id: "p1", name: "Marketing", description: "Send promotional content", isPrimary: true, necessity: "non-essential", automatedProcessing: false, profilingUsage: true }],
        status: "active",
        version: "2.1",
        noExpiry: false,
        validityStart: "2024-01-01",
        validityEnd: "2025-01-01",
        targetUserCategory: ["customer"],
        ageThreshold: 18,
        consentGivenBy: "self",
        dataCategories: [{ category: "contact", label: "Contact Data", mandatory: true, source: "direct" }],
        mechanism: "checkbox",
        separateConsents: true,
        withdrawVisible: true,
        dataSharing: true,
        thirdParties: [],
        subProcessors: [],
        retention: { period: "2 years", justification: "Marketing campaign duration", autoDelete: true, postWithdrawalRules: "Delete within 30 days" },
        security: { encryptionAtRest: true, encryptionInTransit: true, accessControls: true, monitoringLogging: true, incidentResponse: true, certifications: ["ISO 27001"], additionalMeasures: [] },
        withdrawal: { method: "Email or portal", effect: "No more marketing emails", rightsLink: "/rights", processingTimeline: "7 days" },
        privacyNoticeRef: "PN-2024-001",
        auditTrailEnabled: true,
        defaultLanguage: "en",
        supportedLanguages: ["en", "hi"],
        createdBy: "Admin User",
        createdAt: "2024-01-15",
        updatedAt: "2024-01-20",
        updatedBy: "Admin User",
    },
    {
        id: "tpl-002",
        name: "Data Analytics Processing",
        description: "Consent for using personal data for analytics and insights",
        type: "explicit",
        regulations: ["DPDP", "TAPA"],
        purposes: [{ id: "p2", name: "Analytics", description: "Generate usage insights", isPrimary: true, necessity: "non-essential", automatedProcessing: true, profilingUsage: true }],
        status: "active",
        version: "1.0",
        noExpiry: true,
        targetUserCategory: ["customer", "employee"],
        ageThreshold: 18,
        consentGivenBy: "self",
        dataCategories: [{ category: "behavioral", label: "Behavioral Data", mandatory: true, source: "direct" }],
        mechanism: "toggle",
        separateConsents: true,
        withdrawVisible: true,
        dataSharing: false,
        thirdParties: [],
        subProcessors: [],
        retention: { period: "3 years", justification: "Analytics retention policy", autoDelete: true, postWithdrawalRules: "Anonymize data" },
        security: { encryptionAtRest: true, encryptionInTransit: true, accessControls: true, monitoringLogging: true, incidentResponse: true, certifications: [], additionalMeasures: [] },
        withdrawal: { method: "Settings page", effect: "Data excluded from analytics", rightsLink: "/rights", processingTimeline: "3 days" },
        privacyNoticeRef: "PN-2024-002",
        auditTrailEnabled: true,
        defaultLanguage: "en",
        supportedLanguages: ["en"],
        createdBy: "DPO",
        createdAt: "2024-02-01",
        updatedAt: "2024-02-01",
        updatedBy: "DPO",
    },
    {
        id: "tpl-003",
        name: "Third-Party Data Sharing",
        description: "Consent for sharing data with partner organizations",
        type: "explicit",
        regulations: ["GDPR", "PDPL"],
        purposes: [{ id: "p3", name: "Partner Sharing", description: "Share with business partners", isPrimary: true, necessity: "non-essential", automatedProcessing: false, profilingUsage: false }],
        status: "draft",
        version: "0.5",
        noExpiry: false,
        validityStart: "2024-03-01",
        targetUserCategory: ["customer"],
        ageThreshold: 18,
        consentGivenBy: "self",
        dataCategories: [{ category: "identity", label: "Identity Data", mandatory: true, source: "direct" }],
        mechanism: "signature",
        separateConsents: true,
        withdrawVisible: true,
        dataSharing: true,
        thirdParties: [{ id: "tp1", name: "Partner Corp", role: "data-processor", purpose: "Service delivery", country: "USA", crossBorderTransfer: true }],
        subProcessors: [],
        retention: { period: "1 year", justification: "Contract duration", autoDelete: false, postWithdrawalRules: "Notify partner" },
        security: { encryptionAtRest: true, encryptionInTransit: true, accessControls: true, monitoringLogging: true, incidentResponse: true, certifications: ["SOC 2"], additionalMeasures: [] },
        withdrawal: { method: "Written request", effect: "Stop data sharing", rightsLink: "/rights", processingTimeline: "14 days" },
        privacyNoticeRef: "PN-2024-003",
        auditTrailEnabled: true,
        defaultLanguage: "en",
        supportedLanguages: ["en", "ar"],
        createdBy: "Legal Team",
        createdAt: "2024-02-15",
        updatedAt: "2024-02-18",
        updatedBy: "Legal Team",
    },
    {
        id: "tpl-004",
        name: "Essential Service Consent",
        description: "Mandatory consent for core service delivery",
        type: "mandatory",
        regulations: ["DPDP"],
        purposes: [{ id: "p4", name: "Service Delivery", description: "Provide core services", isPrimary: true, necessity: "essential", automatedProcessing: true, profilingUsage: false }],
        status: "active",
        version: "3.0",
        noExpiry: true,
        targetUserCategory: ["customer"],
        ageThreshold: 18,
        consentGivenBy: "self",
        dataCategories: [{ category: "identity", label: "Identity Data", mandatory: true, source: "direct" }, { category: "contact", label: "Contact Data", mandatory: true, source: "direct" }],
        mechanism: "click-to-confirm",
        separateConsents: false,
        withdrawVisible: true,
        dataSharing: false,
        thirdParties: [],
        subProcessors: [],
        retention: { period: "Duration of service", justification: "Required for service", autoDelete: false, postWithdrawalRules: "Retain as per law" },
        security: { encryptionAtRest: true, encryptionInTransit: true, accessControls: true, monitoringLogging: true, incidentResponse: true, certifications: ["ISO 27001", "SOC 2"], additionalMeasures: [] },
        withdrawal: { method: "Account deletion", effect: "Service termination", rightsLink: "/rights", processingTimeline: "30 days" },
        privacyNoticeRef: "PN-2024-004",
        auditTrailEnabled: true,
        defaultLanguage: "en",
        supportedLanguages: ["en", "hi", "ta", "te"],
        createdBy: "Admin User",
        createdAt: "2023-12-01",
        updatedAt: "2024-01-10",
        updatedBy: "DPO",
    },
    {
        id: "tpl-005",
        name: "Minor Data Processing",
        description: "Consent for processing data of users under 18",
        type: "explicit",
        regulations: ["DPDP", "GDPR", "TAPA"],
        purposes: [{ id: "p5", name: "Minor Services", description: "Age-appropriate services", isPrimary: true, necessity: "essential", automatedProcessing: false, profilingUsage: false }],
        status: "archived",
        version: "1.2",
        noExpiry: false,
        validityStart: "2023-06-01",
        validityEnd: "2024-01-01",
        targetUserCategory: ["minor", "guardian"],
        ageThreshold: 13,
        consentGivenBy: "guardian",
        dataCategories: [{ category: "identity", label: "Identity Data", mandatory: true, source: "direct" }],
        mechanism: "signature",
        separateConsents: true,
        withdrawVisible: true,
        dataSharing: false,
        thirdParties: [],
        subProcessors: [],
        retention: { period: "Until age 18", justification: "Minor protection", autoDelete: true, postWithdrawalRules: "Immediate deletion" },
        security: { encryptionAtRest: true, encryptionInTransit: true, accessControls: true, monitoringLogging: true, incidentResponse: true, certifications: [], additionalMeasures: [] },
        withdrawal: { method: "Guardian request", effect: "Data deletion", rightsLink: "/rights", processingTimeline: "7 days" },
        privacyNoticeRef: "PN-2023-005",
        auditTrailEnabled: true,
        defaultLanguage: "en",
        supportedLanguages: ["en"],
        createdBy: "Legal Team",
        createdAt: "2023-06-01",
        updatedAt: "2023-12-15",
        updatedBy: "Legal Team",
    },
    {
        id: "tpl-006",
        name: "Cross-Border Analytics Consent",
        description: "Consent for analytics processing with approved overseas processors",
        type: "granular",
        regulations: ["DPDP", "GDPR", "PDPL"],
        purposes: [{ id: "p6", name: "Cross-Border Analytics", description: "Regional behavior analytics", isPrimary: true, necessity: "non-essential", automatedProcessing: true, profilingUsage: true }],
        status: "active",
        version: "1.4",
        noExpiry: false,
        validityStart: "2024-03-01",
        validityEnd: "2026-03-01",
        targetUserCategory: ["customer", "vendor"],
        ageThreshold: 18,
        consentGivenBy: "self",
        dataCategories: [
            { category: "behavioral", label: "Behavioral Data", mandatory: true, source: "direct" },
            { category: "location", label: "Location Data", mandatory: false, source: "direct" }
        ],
        mechanism: "toggle",
        separateConsents: true,
        withdrawVisible: true,
        dataSharing: true,
        thirdParties: [{ id: "tp2", name: "Insights EU GmbH", role: "data-processor", purpose: "Audience analytics", country: "Germany", crossBorderTransfer: true }],
        subProcessors: [{ id: "sp1", name: "Cloud Lakehouse", purpose: "Data storage", country: "Netherlands", changeNotification: true }],
        retention: { period: "18 months", justification: "Campaign analysis cycles", autoDelete: true, postWithdrawalRules: "Anonymize within 14 days" },
        security: { encryptionAtRest: true, encryptionInTransit: true, accessControls: true, monitoringLogging: true, incidentResponse: true, certifications: ["ISO 27001", "SOC 2"], additionalMeasures: [] },
        withdrawal: { method: "In-app privacy center", effect: "Stop behavioral processing", rightsLink: "/rights", processingTimeline: "5 days" },
        privacyNoticeRef: "PN-2024-006",
        auditTrailEnabled: true,
        defaultLanguage: "en",
        supportedLanguages: ["en", "hi", "fr", "de"],
        createdBy: "Privacy Ops",
        createdAt: "2024-03-02",
        updatedAt: "2024-06-12",
        updatedBy: "Privacy Ops",
    },
    {
        id: "tpl-007",
        name: "Employee Wellness Data Consent",
        description: "Optional consent for wellness program insights and recommendations",
        type: "optional",
        regulations: ["DPDP", "Custom"],
        purposes: [{ id: "p7", name: "Wellness Insights", description: "Personalized wellness nudges", isPrimary: true, necessity: "non-essential", automatedProcessing: true, profilingUsage: true }],
        status: "draft",
        version: "0.9",
        noExpiry: true,
        targetUserCategory: ["employee"],
        ageThreshold: 18,
        consentGivenBy: "self",
        dataCategories: [
            { category: "health", label: "Health Data", mandatory: false, source: "direct" },
            { category: "behavioral", label: "Activity Data", mandatory: false, source: "direct" }
        ],
        mechanism: "checkbox",
        separateConsents: true,
        withdrawVisible: true,
        dataSharing: false,
        thirdParties: [],
        subProcessors: [],
        retention: { period: "12 months", justification: "Monthly wellness reports", autoDelete: true, postWithdrawalRules: "Delete recommendations history" },
        security: { encryptionAtRest: true, encryptionInTransit: true, accessControls: true, monitoringLogging: true, incidentResponse: true, certifications: ["ISO 27001"], additionalMeasures: [] },
        withdrawal: { method: "HR portal", effect: "Program recommendations disabled", rightsLink: "/rights", processingTimeline: "2 days" },
        privacyNoticeRef: "PN-2024-007",
        auditTrailEnabled: true,
        defaultLanguage: "en",
        supportedLanguages: ["en", "hi"],
        createdBy: "HR Compliance",
        createdAt: "2024-07-01",
        updatedAt: "2024-07-08",
        updatedBy: "HR Compliance",
    },
    {
        id: "tpl-008",
        name: "Legacy SMS Promotion Consent",
        description: "Deprecated consent template retained for audit continuity",
        type: "implicit",
        regulations: ["GDPR", "DPDP"],
        purposes: [{ id: "p8", name: "SMS Promotions", description: "Outbound SMS marketing", isPrimary: true, necessity: "non-essential", automatedProcessing: false, profilingUsage: false }],
        status: "deprecated",
        version: "4.6",
        noExpiry: false,
        validityStart: "2021-01-01",
        validityEnd: "2024-12-31",
        targetUserCategory: ["customer"],
        ageThreshold: 18,
        consentGivenBy: "self",
        dataCategories: [{ category: "contact", label: "Phone Number", mandatory: true, source: "direct" }],
        mechanism: "click-to-confirm",
        separateConsents: false,
        withdrawVisible: true,
        dataSharing: false,
        thirdParties: [],
        subProcessors: [],
        retention: { period: "6 months", justification: "Regulatory retention", autoDelete: true, postWithdrawalRules: "Purge communication logs" },
        security: { encryptionAtRest: true, encryptionInTransit: true, accessControls: true, monitoringLogging: true, incidentResponse: true, certifications: [], additionalMeasures: [] },
        withdrawal: { method: "SMS STOP reply", effect: "No further promotional SMS", rightsLink: "/rights", processingTimeline: "24 hours" },
        privacyNoticeRef: "PN-2021-011",
        auditTrailEnabled: true,
        defaultLanguage: "en",
        supportedLanguages: ["en"],
        createdBy: "Marketing Ops",
        createdAt: "2021-01-10",
        updatedAt: "2024-01-05",
        updatedBy: "DPO",
    },
];
